all: prepare train test

prepare:
	@echo "Prepare Images"
	python ./module/food/prepare.py

train:
	@echo "Training model"
	python ./module/food/train.py

test:
	@echo "Testing model"
	python ./module/food/test.py
